### PR TITLE
Lua API for LibEXIF v1 and v2

### PR DESCRIPTION
**Pull request by GitSparTV**
Hi @capr 
I've made a simple API for Libexif on Lua.
This allows to:

1. Read EXIF data from file
2. Get tags table if they're found. (Automatically fixes them to try return something)
3. Free EXIF object

ffi.C moved to _module_.C
Added libexif_test.lua
Updated libexif.md
Added an object **ExifData** has _GetTags_ and _free_ function and _.raw_ key for _cdata_ obejct.

Any others functions can be done by _module_.C, this API was created only for reading tags.

Requesting to merge. Thanks

### CODE REVIEW

**Comment by capr** [comment]
Thanks. Just a couple of points:

* please use the snake_case_convention for identifiers for consistency with other libs.
* since you made libexif_test.lua, please move all testing code from libexif.lua too.
* ffi callbacks are a very limited resource (there are 500 - 1000 total that you can make), so you need to create them manually, keep them somewhere and free them after you're done with the file.
* please allocate a single 1024 bytes buffer for the entire operation and free it afterwards (also, allocating like you did is undefined behavior, i.e. by the time you call ffi.string() on it, it might already been freed since no one points to it from Lua).
* what is the purpose of passing `newproxy()` ?
* please bind an open that reads from memory instead of from a file name, this way I can use the `fs` module to open the file, instead of libexif which probably doesn't use `CreateFile` internally on Windows and thus cannot open files with characters other than ASCII.

**Comment by GitSparTV** [comment]
@capr 
Thanks for tips about ffi. Not so much information were found by me about it. 
I don't know C language at all so I was trying to figure out by information that I've found.

> * please use the snake_case_convention for identifiers for consistency with other libs.

Didn't know the rules of style so I used the one I know. GetKeys -> get_keys

> * since you made libexif_test.lua, please move all testing code from libexif.lua too.

libexif_test has the test code to validate itself. The code in libexif is a demo. Maybe I should move it to libexif_demo.lua?

> * ffi callbacks are a very limited resource (there are 500 - 1000 total that you can make), so you need to create them manually, keep them somewhere and free them after you're done with the file.

So should I call automatically all functions and store the results in already in object?

> * please allocate a single 1024 bytes buffer for the entire operation and free it afterwards (also, allocating like you did is undefined behavior, i.e. by the time you call ffi.string() on it, it might already been freed since no one points to it from Lua).

So I need to ffi.gc it?

> * what is the purpose of passing `newproxy()` ?

This is the only thing that I forgot to change, I found table of converting only after I've set newproxy. I'll change it to `nil`.

> * please bind an open that reads from memory instead of from a file name, this way I can use the `fs` module to open the file, instead of libexif which probably doesn't use `CreateFile` internally on Windows and thus cannot open files with characters other than ASCII.

I'll try to. Will it be ok if it require a `fs` dependency after?

**Comment by capr** [comment]
Re ffi callbacks: you need to 
  1) typedef the function pointer in ffi.cdef if it's not already.
  2) create the ffi callback object explicitly with ffi.cast('function_ptr_type', your_lua_function)
  3) pass the callback object to the C function expecting it
  4) when you're done with the iterator, free the callback object with cb:free()
See expat.lua, giflib.lua, libcurl.lua, libpng.lua, librsync.lua, luastate.lua for how to use callbacks efficiently.

Re the 1024 buffer, you can do better than ffi.gc which is asynchronous, you can simply call ffi.free() on it when you're done with it.

Re `fs` dependency: IMHO libraries that work on data like libexif should not depend on a filesystem API. Let the user sort that out in its own code. This is why you won't find a way to open a file in libjpeg.lua for instance. In libexif_test.lua you can use `glue.readfile()` to get the contents of a file in a string in one line.

**Comment by GitSparTV** [comment]
@capr 
I need a little explanation about `ffi.free()`. There's no function like that.
`ffi.new("char[1024]")` doesn't have **free** method. What I need to to with it and without `ffi.gc` as you said?

Everything else seems done for me and ready to commit

**Comment by capr** [comment]
@GitSparTV Oh, sorry my bad, you're right, ffi.new() allocates to Lua's heap, so no ffi.free(). Just allocate a single buffer at the beginning of the iteration if you can, it's subject to Lua's gc already, no need to tie ffi.gc to it (and in fact there's nothing you can even do in ffi.gc for it).

**Comment by GitSparTV** [comment]
@capr 
So I would leave it as it is? One thing I made with it is it's not for every thing in foreach

**Comment by GitSparTV** [comment]
@capr 
Version 2
Please check for changes

**Review by capr — APPROVED** [review]

**Comment by capr** [comment]
Btw, why not use ffi.metatype around ExifLoader objects instead of wrapping in a Lua table? And why not allow a cdata buffer too in addition to a Lua string?

**Comment by capr** [comment]
```
	if edata == nil then
		C.exif_data_free(edata)
```

this doesn't look right. Freeing a nil pointer?

**Comment by GitSparTV** [comment]
Oh, right, if it becomes lua-nil then this will errors.
I tried to return False when csdata is C-NULL.

**Comment by GitSparTV** [comment]
`cdata<struct _ExifData *>: NULL` this is how it looks when data is empty or not valid.
Should I maybe use ffi.NULL to compare?

**Comment by GitSparTV** [comment]
@capr 
> Btw, why not use ffi.metatype around ExifLoader objects instead of wrapping in a Lua table? And why not allow a cdata buffer too in addition to a Lua string?

Because I'm literally doing ffi for the first time. Maybe due to my only-lua knowledges the ffi tutorials on LuaJIT site are not enough to understand, but somehow I did it.

**Comment by GitSparTV** [comment]
I'm making 3rd version with fixes and notes

**Pull request merged**
