### PR TITLE
Lua API for LibEXIF v3

### PR DESCRIPTION
**Pull request by GitSparTV**
@capr 

- Changed nil to ffi.NULL
- Cdata now wrapped in metatype, not in lua metatable with key to cdata.
- Fixed .md
- JPEG and path changed to file

Requesting to merge. Thanks

### CODE REVIEW

**Comment by capr** [comment]
I already fixed the docs for you, now you have to pull to fix conflicts.

**Comment by GitSparTV** [comment]
The API changed.
For example `The cdata object stored in exif_data.raw` in .md is now wrong. Now `exif_data` itself returns cdata

**Comment by capr** [comment]
You still have to _fix the conflicts_

**Comment by capr** [comment]
```
if edata == ffi.NULL then
		C.exif_data_free(edata)			
```
this is still not good, edata == nil works just fine, that's not the problem. The problem is that you're calling `C.exif_data_free(nil)` what's that going to do? Try it out maybe.

**Comment by capr** [comment]
You can't assign a metatype in the read() function. Try it out, it won't work to assign it twice. Read about it here: http://luajit.org/ext_ffi_api.html

**Comment by GitSparTV** [comment]
> You can't assign a metatype in the read() function. Try it out, it won't work to assign it twice. Read about it here: http://luajit.org/ext_ffi_api.html

So I need to call it once and then use ffi.new("ExifData*") as before?

UPD: Seems working

**Comment by GitSparTV** [comment]
> You can't assign a metatype in the read() function. Try it out, it won't work to assign it twice. Read about it here: http://luajit.org/ext_ffi_api.html

@capr 
When data is corrupted or not EXIF data were found it becomes empty struct: `cdata<struct _ExifData *>: NULL`

Maybe I don't have to free it?

**Comment by capr** [comment]
How can you free a nil pointer???

**Comment by capr** [comment]
That's not an "empty struct" (there's no such thing). That's a pointer to the memory address `0`, i.e. a null pointer.

**Comment by GitSparTV** [comment]
That's my ignorance in C. I thought if it still prints as struct then it's not totally free.
Sorry for such questions.

**Comment by GitSparTV** [comment]
- Removed free call on null pointer
- Solved .md conflicts

**Comment by GitSparTV** [comment]
Thanks

**Comment by capr** [comment]
:thumbsup:

**Pull request merged**
